#!/bin/bash
WD=$PWD
rm -rf /root/ubuntu20.04
git clone git@github.com:dOC4eVER/ubuntu20.04.git /root/ubuntu20.04
reprepro --keepunreferencedfiles -Vb /root/ubuntu20.04/package/Ubuntu/ includedeb focal $1
cp /root/ubuntu20.04/package/Ubuntu/dists/focal/Release /root/ubuntu20.04/package/Ubuntu/dists/focal/InRelease
cd /root/ubuntu20.04/
git add *
git commit -m "add Ubuntu 20.04 packages"
git push -u origin master
cd $WD
rm -f $1
