#!/bin/bash
rm -rf /root/ubuntu20.04
git clone git@github.com:dOC4eVER/ubuntu20.04.git /root/ubuntu20.04
NAMERPM=$(rpm -pq --queryformat "%{NAME}" $1)
MINRPM=${NAMERPM::1}
mkdir -p /root/ubuntu20.04/package/Fedora/35/x86_64/Packages/$MINRPM
mv $1 /root/ubuntu20.04/package/Fedora/35/x86_64/Packages/$MINRPM
createrepo --update /root/ubuntu20.04/package/Fedora/35/x86_64
cd /root/ubuntu20.04/
git add *
git commit -m "add Fedora 35 packages"
git push -u origin master
